# -*- coding: utf-8 -*-
"""Laboratorio 4 - Parte 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/sergioalib/448c9ed3d7e7710f871104d7a7a48686/laboratorio-4-parte-3.ipynb

Obtencion de datos del Huracan Iota
"""

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/321/12/OR_GLM-L2-LCFA_G16_s20203211200000_e20203211200204_c20203211200226.nc

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/321/12/OR_GLM-L2-LCFA_G16_s20203211200200_e20203211200405_c20203211200424.nc

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/321/12/OR_GLM-L2-LCFA_G16_s20203211200400_e20203211201005_c20203211201027.nc

"""Obtencion de datos del Huracan Eta"""

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/307/12/OR_GLM-L2-LCFA_G16_s20203071200000_e20203071200204_c20203071200223.nc

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/307/12/OR_GLM-L2-LCFA_G16_s20203071200200_e20203071200404_c20203071200425.nc

!wget https://noaa-goes16.s3.amazonaws.com/GLM-L2-LCFA/2020/307/12/OR_GLM-L2-LCFA_G16_s20203071200400_e20203071201004_c20203071201025.nc

"""se cambiaron el nombre de los archivos por eta.nc y iota.nc para un mejor manejo

"""

from netCDF4 import Dataset

"""Empezamos con el huracan Iota"""

diota=Dataset('/content/iota.nc')

diota

"""Queremos los datos de eventos, grupos y flashes"""

import pylab as plt

"""Eventos

"""

ieventlat=diota.variables['event_lat'][:]
ieventlon=diota.variables['event_lon'][:]

plt.title('Eventos Huracán Iota 12:00:00 UTC')
plt.scatter(ieventlon,ieventlat)

"""Grupos"""

igruplat=diota.variables['group_lat'][:]
igruplon=diota.variables['group_lon'][:]

plt.title('Grupos Huracán Iota 12:00:00 UTC')
plt.scatter(igruplon, igruplat)

"""Flash"""

iflashlat=diota.variables['flash_lat'][:]
iflahslon=diota.variables['flash_lon'][:]

plt.title('Flash Huracán Iota 12:00:00 UTC')
plt.scatter(iflahslon,iflashlat)

"""20 segundos despues

"""

diota20=Dataset('/content/iota20.nc')
diota20

"""eventos"""

ieventlat20=diota20.variables['event_lat'][:]
ieventlon20=diota20.variables['event_lon'][:]

plt.title('Eventos Huracán Iota 12:00:20 UTC')
plt.scatter(ieventlon20,ieventlat20)

"""grupos"""

igrouplat20=diota20.variables['group_lat'][:]
igrouplon20=diota20.variables['group_lon'][:]

plt.title('Grupos Huracán Iota 12:00:20 UTC')
plt.scatter(igrouplon20,igrouplat20)

iflashlat20=diota20.variables['flash_lat'][:]
iflashlon20=diota20.variables['flash_lon'][:]

plt.title('Flash Huracán Iota 12:00:20 UTC')
plt.scatter(iflashlon20,iflashlat20)

"""Ahora 40 segundos a partir del tiempo inicial"""

diota40=Dataset('/content/iota40.nc')
diota40

"""eventos"""

ieventlat40=diota40.variables['event_lat'][:]
ieventlon40=diota40.variables['event_lon'][:]

plt.title('Eventos Huracán Iota 12:00:40 UTC')
plt.scatter(ieventlon40,ieventlat40)

"""grupos"""

igrouplat40=diota40.variables['group_lat'][:]
igrouplon40=diota40.variables['group_lon'][:]

plt.title('Grupos Huracán Iota 12:00:40 UTC')
plt.scatter(igrouplon40,igrouplat40)

"""Flash"""

iflashlat40=diota40.variables['flash_lat'][:]
iflashlon40=diota40.variables['flash_lon'][:]

plt.title('Flash Huracán Iota 12:00:40 UTC')
plt.scatter(iflashlon40,iflashlat40)

"""**Ahora con el Huracán Eta**

"""

deta=Dataset('/content/eta.nc')

deta

"""Eventos"""

eeventlat=deta.variables['event_lat'][:]
eeventlon=deta.variables['event_lon'][:]

plt.title('Eventos Huracán Eta 12:00:00 UTC')
plt.scatter(eeventlon,eeventlat)

"""Grupos"""

egrouplat=deta.variables['group_lat'][:]
egrouplon=deta.variables['group_lon'][:]
plt.title('Grupos Huracán Eta 12:00:00 UTC')
plt.scatter(egrouplon,egrouplat)

eflashlat=deta.variables['flash_lat'][:]
eflashlon=deta.variables['flash_lon'][:]
plt.title('Flash Huracán Eta 12:00:00 UTC')
plt.scatter(eflashlon,eflashlat)

"""20 segundos despues"""

deta20=Dataset('/content/eta20.nc')

"""eventos"""

eeventlat20=deta20.variables['event_lat'][:]
eeventlon20=deta20.variables['event_lon'][:]
plt.title('Eventos Huracán Eta 12:00:20 UTC')
plt.scatter(eeventlon20,eeventlat20)

"""grupos"""

egrouplat20=deta20.variables['group_lat'][:]
egrouplon20=deta20.variables['group_lon'][:]
plt.title('Grupos Huracán Eta 12:00:20 UTC')
plt.scatter(egrouplon20,egrouplat20)

"""flash"""

eflashlat20=deta20.variables['flash_lat'][:]
eflashlon20=deta20.variables['flash_lon'][:]
plt.title('Flash Huracán Eta 12:00:20 UTC')
plt.scatter(eflashlon20,eflashlat20)

"""Ahora 40 segundos despues del inicial"""

deta40=Dataset('/content/eta40.nc')

"""Eventos"""

eeventlat40=deta40.variables['event_lat'][:]
eeventlon40=deta40.variables['event_lon'][:]
plt.title('Eventos Huracán Eta 12:00:40 UTC')
plt.scatter(eeventlon40,eeventlat40)

"""Grupos"""

egrouplat40=deta40.variables['group_lat'][:]
egrouplon40=deta40.variables['group_lon'][:]
plt.title('Grupos Huracán Eta 12:00:40 UTC')
plt.scatter(egrouplon40,egrouplat40)

"""Flash"""

eflashlat40=deta40.variables['flash_lat'][:]
eflashlon40=deta40.variables['flash_lon'][:]
plt.title('Flash Huracán Eta 12:00:40 UTC')
plt.scatter(eflashlon40,eflashlat40)